spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://hrms-db:5432/hrms
    username: postgres
    password: postgres123


# Server port
server:
  port: 8080

# CORS URL Configuration
cors:
  origin: http://0.0.0.0:5000